### ISSUE TITLE
ERROR IN DESCRIPTION

### ISSUE THREAD

**Issue by priyachetty01** [projectguru/my_account#107]
PLEASE REMOVE THIS ERROR, IT HAS BEEN THERE SINCE A LONG TIME, ALREADY SUBMITTED A BUG ONCE, BUT NOTHING WAS DONE, IT IS VERY IRRITATING
![error](https://user-images.githubusercontent.com/85338868/186047302-fbbfb9b6-30bb-4805-bf4a-1f51df2e1d6c.png)

**Comment by projectguru** [comment]
done
