### ISSUE TITLE
Which page is it

### ISSUE THREAD

**Issue by siroscelo** [projectguru/my_account#121]
https://www.projectguru.in/how-to-work-with-a-mediating-variable-in-regression/
The statement "Usually, the aim is to identify the impact of the **dependent** variables on the **independent** variables."  shouldn't the statement read  "Usually, the aim is to identify the impact of the **independent** variables on the **dependent** variables."

**Comment by projectguru** [comment]
Yes, you are correct. Thank you for pointing it out.
